apiVersion: v1
kind: Service
metadata:
  name: reddit-service
spec:
  type: LoadBalancer          # request a cloud LB
  selector:
    app: reddit-app
  ports:
    - port: 80                # the port your clients hit
      targetPort: 8000        # your container’s port
      # no nodePort here
